### ISSUE TITLE
Les coordonnées ne fonctionnent pas pour les fichiers générés par outils tels que inkscape

### ISSUE THREAD

**Issue by candaua** [atosorigin/grafana-weathermap-panel#12]
Lorsqu'un outil de génération de fichiers est utilisé pour construire les SVG, les coordonnées ne sont pas correctes dans l'extension, l'origine du repère par exemple n'apparait pas en bas à gauche de l'image comme prévue dans la section 2.3.2 du CCTP

**Comment by hellosct1** [comment]
Après étude du fichier exemple

- L'image doit être en pixel et non en mm
- L'image ne doit pas posséder un cadre (rectangle) dessinée


L'ensemble de ces points seront ajoutés dans la documentation
