### ISSUE TITLE
Les métriques auxiliaires traquent à l'heure actuelle la même query que la primaire, ce qui est incohérent avec le CCTP 

### ISSUE THREAD

**Issue by candaua** [atosorigin/grafana-weathermap-panel#18]
Les métriques auxiliaires sont censées être des métriques additionnelles et facultatives associées aux objets graphiques générés par les métriques principales.
Contrairement aux mesures principales elles n'influencent pas la génération de l'objet graphique, en revanche, leur valeur est affichée comme le serait celle d'une métrique principale.
La section 2.4.4 du CCTP détaille le fonctionnement des métriques auxiliaires

**Comment by candaua** [comment]
Chaque métrique auxiliaire doit avoir ses propres paramètres graphiques pour sa zone de texte, la sous-section "Auxiliary element" de la section "text object" doit donc être répétée autant de fois qu'il y a de métriques + métadonées auxiliaires.

Il n'est pas nécéssaire de créer multiples text objects, en revanche, le sélecteur pour décider si afficher les métriques auxiliaires dans la région texte ou le tooltip est non fonctionnel, il est nécessaire pour avoir l'option d'afficher la valeur des métriques auxiliaires sans survol de l'objet.

**Comment by hellosct1** [comment]
Released 1.0.2
