### ISSUE TITLE
La notion de métadonée auxiliaire est absente.

### ISSUE THREAD

**Issue by candaua** [atosorigin/grafana-weathermap-panel#19]
Les métadonnées auxiliaires, comme les métriques auxiliaires, ne définissent pas l'apparence des objets comme le font les métriques principales.
Comme les métriques auxiliaires, elles s'affichent comme un texte mais contrairement aux métriques auxiliaires leur valeur n'est pas issue d'une mesure mais est simplement un bloc de texte.
La section 2.4.5 du CCTP détaille le fonctionnement de ces métadonnées.

**Comment by hellosct1** [comment]
Released 1.0.2
