### ISSUE TITLE
Pas de mécanisme d'association des données

### ISSUE THREAD

**Issue by candaua** [atosorigin/grafana-weathermap-panel#22]
Conformément à la section et sous-sections 2.5 du CCTP, la solution doit comprendre un mécanisme permettant de générer des objets graphiques pour chaque mesure relevée automatiquement, un exemple de worflow de ce mécanisme est inclus dans le fichier joint [Workflow plugin.docx](https://github.com/atosorigin/grafana-weathermap-panel/files/4769526/Workflow.plugin.docx).

**Comment by hellosct1** [comment]
Released 1.0.2
