### ISSUE TITLE
Ensemble des non-conformités au CCTP

### ISSUE THREAD

**Issue by candaua** [atosorigin/grafana-weathermap-panel#23]
Cette issue regroupe toute les issues concernant le décalage entre la solution et le CCTP en terme de fonctionnalités:
#24 Grafana 7+ non-supporté
#21 Le fonctionnement de l'application ne répond pas au besoin client exprimé
#9 L'image n'est pas redimensionnée pour être entièrement visible
#10 L'espace vectoriel par défaut se base sur l'extension plutôt que le SVG
#11 Les limites d’ordonnées de l'espace vectoriel ne s'appliquent pas
#12 Les coordonnées ne fonctionnent pas pour les fichiers générés par outils tels que inkscape
#16 Il est impossible de faire défiler l'image sans se déplacer dans la fenêtre.
#18 Les métriques auxiliaires traquent à l'heure actuelle la même query que la primaire, ce qui est incohérent avec le CCTP 
#19 La notion de métadonée auxiliaire est absente.
#13 Les liens non directionels sont absents
#14 La légende est difficilement lisible et non-redimensionable.
#22 Pas de mécanisme d'association des données
#20 L'agrégation des métriques semble donner des résultats incorrects.
#17 Les tooltips des métriques et métadonnées auxiliaires sont affichés mêmes quand elles sont vides.

**Comment by hellosct1** [comment]
done
