### ISSUE TITLE
Problèmes de documentation

### ISSUE THREAD

**Issue by candaua** [atosorigin/grafana-weathermap-panel#26]
La documentation présente deux problèmes actuellement:

1-Elle correspond à la livraison de la version 1.0 qui ne correspondait pas au besoin client et doit donc être remaniée pour décrire le fonctionnement de l'application après les changements.

2-Elle comprend des liens morts (par exemple la section "More and less" de la page https://github.com/atosorigin/grafana-weathermap-panel/tree/master/docs)

Concernant ce second problème, cette issue peut être utiliser pour signaler la présence de liens morts dont la résolution pourra être marquée par un commentaire par la suite.

**Comment by hellosct1** [comment]
Released 1.0.2
