### ISSUE TITLE
InfluxDB datasource, cannot see the query

### ISSUE THREAD

**Issue by Franz1983** [atosorigin/grafana-weathermap-panel#33]
Hello,
i've just installed the plugin on Grafana 6.7.4 but i've an issue as i cannot see the query i define.
Following the guide, after creating a Region, browsing in the tab Coordinates space ->Region -> Edit coordinate space -> Main metri  i cannot see the query i've defined in the drop down menu 'Query'.
As from the subject i' using an influxDB datasource... is there a particular way i have to compose the query ? I cannot figure out of this issue..

**Comment by hellosct1** [comment]
hi,

the plugin is compatible as a datasource with Prometheus

Thanks
