### ISSUE TITLE
Broken link: https://grafana.com/plugins/grafana-weathermap-panel

### ISSUE THREAD

**Issue by minfrin** [atosorigin/grafana-weathermap-panel#5]
The link to the grafana page for https://grafana.com/plugins/grafana-weathermap-panel is returning 404 Not Found.

**Comment by hellosct1** [comment]
Hi,

we are currently waiting for confirmation of validation by Grafana for the link to work.

For the moment, you have to either download the ZIP or follow the installation information manually which is explained on the following page

https://github.com/atosorigin/grafana-weathermap-panel/blob/master/docs/EN/init/installation.md

Thanks

**Comment by minfrin** [comment]
Alas, installation no longer works - grafana 7 and up requires plugins to be signed.

We had the grafana-weathermap-panel installed in grafana 6.7, but the plugin disappeared after we upgraded.

Please reopen if possible until this is fixed.
