### ISSUE TITLE
Docs confusion: how to upload an SVG image

### ISSUE THREAD

**Issue by minfrin** [atosorigin/grafana-weathermap-panel#6]
I'm raising this to document confusion I'm having over the uploading of an SVG file.

Following the principle of least surprise, I tried to upload a file using the "Multi Local Import". After doing this nothing obvious happened. The file was listed, but this didn't seem to do anything or cause anything to happen.

I then went digging and uncovered the "Image" field, a free form text box. The box has no hint as to what should go in it. Various docs showed different competing values for this box. In one case it was a relative path pointing at a file, but no clue as to how or why the value was as it was. In another case the value was an URL pointing at a file on http://localhost/. In this case it was clear what the significance of localhost was, was this just for testing? Was it supposed to be localhost?

Eventually I guessed and put the name of the file I uploaded above into the field. At this point a bouncing grafana logo appears saying "Loading Grafana", and this stays this way. I tried to change the name to have a leading slash, and suddenly the screen changed to have a background saying "Not Found".

The "upload a file" option needs to be looked at and made clearer, it is very confusing as it stands.

**Comment by minfrin** [comment]
More confusing docs: https://github.com/atosorigin/grafana-weathermap-panel/blob/master/docs/EN/init/introduction.md

"Step 4 : On the visualization menu, you will be able to choose your background (SVG image, Bitmap image, or no image)"

- What is the "visualization menu"?
- If the "visualization menu" is the mechanism where you choose the weatherdmap plugin, how do you, once you've chosen the weathermap plugin, how do you choose your background?

This needs to be updated so it's clear how to specify the SVG.

**Comment by hellosct1** [comment]
hi,

thank you for the message

we have added the possibility to upload a file from his computer with the new version we've just deployed

we have also added a tutorial that shows how to do it.

https://github.com/atosorigin/grafana-weathermap-panel/blob/master/docs/EN/demo/tutorial12.md

do not hesitate to send us feedback

**Comment by minfrin** [comment]
Will definitely try this as soon as we can get past https://github.com/atosorigin/grafana-weathermap-panel/issues/7 - thanks for this.

The https://github.com/atosorigin/grafana-weathermap-panel/blob/master/docs/EN/demo/tutorial12.md docs look like you're running grafana locally, I'm assuming for development work. We have a grafana deployed as a server aimed at network admins, they won't be running anything locally.

**Comment by hellosct1** [comment]
Hi,


this tutorial is for running locally
but companies that use in production (like us), have servers and you can watch the following tutorial 

https://github.com/atosorigin/grafana-weathermap-panel/blob/master/docs/EN/demo/tutorial10.md

or the others that show a lot https://github.com/atosorigin/grafana-weathermap-panel/tree/master/docs/EN/demo

best regard
