### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by minfrin** [atosorigin/grafana-weathermap-panel#7]
When attempting to edit an existing panel, the following mapped error appears:

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

The full output is as follows:

```
An unexpected error happened
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    in div
    in Display
    in div
    in Ma
    in div
    in SimpleEditor
    in div
    in div
    in Wn
    in Unknown
    in Dn
    in Yr
    in div
    in div
    in t
    in t
    in div
    in Ma
    in div
    in div
    in po
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in m
    in Unknown
    in Unknown
    in t
    in t
    in s
```

**Comment by minfrin** [comment]
Looks like the plugin is broken from grafana 7.0.0 onwards.

**Comment by hellosct1** [comment]
Hi,

the plugin is currently not compatible with Grafana 7.0.x because they have modified the construction of the editor

regarding the error message you have, we are interested in having more information or the procedure you did to get this message.

thanks

**Comment by minfrin** [comment]
Install grafana 6.7 from RPM on centos8, deploy grafana-weathermap-panel.

Using "dnf update", upgrade grafana to 7.

From this point on any attempt to use grafana-weathermap-panel triggers this error.

**Comment by hellosct1** [comment]
Hi,

Thank you for your message, which means you're on Grafana 7.

We know that the version has been available for a few days but currently the plugin is not compatible with this version.

we are sorry

best regard

**Comment by minfrin** [comment]
Just a heads up - if you use the grafana RPM repos, they place all releases into the same repo, including major releases.

Anyone who does a "dnf upgrade" on the machine will get the grafana upgrade, and your plugin will break.

I am assuming by closing this issue you have no plans to support grafana 7 in the future?
